name: flutter_blog
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  device_preview: ^1.1.0
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  http: ^1.2.0
  image_picker: ^1.1.1
  intl: ^0.19.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/