// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt2hEGYk2-AD2sqRvxeJG3PMBGvf_3LEk',
    appId: '1:127026209811:web:8ce77de6a887be0c818be6',
    messagingSenderId: '127026209811',
    projectId: 'flutter-blog-noticias',
    authDomain: 'flutter-blog-noticias.firebaseapp.com',
    storageBucket: 'flutter-blog-noticias.appspot.com',
    measurementId: 'G-DE56DYPJG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVagMvhLHZtHvgQwEr8psi8iyfWph5vQc',
    appId: '1:127026209811:android:2701b7ff21896f8d818be6',
    messagingSenderId: '127026209811',
    projectId: 'flutter-blog-noticias',
    storageBucket: 'flutter-blog-noticias.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD14M_ovYM6JtR257yLCyvbVkh3WC5I1uY',
    appId: '1:127026209811:ios:5bbf8260b97f4201818be6',
    messagingSenderId: '127026209811',
    projectId: 'flutter-blog-noticias',
    storageBucket: 'flutter-blog-noticias.appspot.com',
    iosBundleId: 'com.example.flutterBlog',
  );
}
